apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-apache
  labels:
    app: playground-apache
    type: web
spec:
  selector:
    matchLabels:
      app: playground-apache
  replicas: 1
  template:
    metadata:
      labels:
        app: playground-apache
        type: web
    spec:
      containers:
      - name: playground-apache
        image: playground-apache:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: apache-persistent-storage
        hostPath: 
          path: <APACHE-PERSISTENT-STORAGE>