apiVersion: v1
kind: Service
metadata:
  name: playground-apache
  labels:
    app: playground-apache
    type: web
spec:
  type: NodePort
  ports:
   - name: apache
     port: 80
     targetPort: 80
     nodePort: 30080
  selector:
   app: playground-apache