apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playground-postgres-data-pvc
  labels:
    app: playground-postgres
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi