apiVersion: v1
kind: Service
metadata:
  name: playground-postgres
  labels:
    app: playground-postgres
    type: db
spec:
  selector:
    app: playground-postgres
    type: db
  type: NodePort
  ports:
  - name: psql
    port: 5432
    nodePort: 30081